USE Vibe;
GO


DROP TABLE IF EXISTS MESSAGES;
DROP TABLE IF EXISTS CHAT;
DROP TABLE IF EXISTS TICKETS;
DROP TABLE IF EXISTS ITEMS;
DROP TABLE IF EXISTS RESERVES;
DROP TABLE IF EXISTS SPACES;
DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROL;
